name: Dataset Curation Issue
description: Use this template to track dataset curation progress
title: "[Dataset]: "
labels: ["ready"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        # Dataset Curation Tracking
        
        Please provide the following information to track this dataset through the curation pipeline.

  - type: input
    id: title
    attributes:
      label: Dataset Title
      description: Enter the title of the dataset
      placeholder: ex. Single-cell RNA-seq of mouse cortical cells
    validations:
      required: true

  - type: input
    id: pmid
    attributes:
      label: PubMed ID (PMID)
      description: Enter the PubMed ID associated with this dataset
      placeholder: ex. 12345678
    validations:
      required: true
  
  - type: input
    id: sra
    attributes:
      label: SRA Accession
      description: Enter the SRA accession number(s) for this dataset
      placeholder: ex. SRX123456 or multiple separated by commas
    validations:
      required: true
      
  - type: dropdown
    id: status
    attributes:
      label: Current Status
      description: Select the current status of this dataset
      options:
        - ready
        - curation ongoing
        - processing ongoing
        - done
    validations:
      required: true
      
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Add any relevant notes or comments about this dataset
      placeholder: Include any special processing requirements, issues, or other relevant information.
    validations:
      required: false